# git-cliff configuration for oprf-nr
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

"""
body = """
{%- macro remote_url() -%}
  https://github.com/TaceoLabs/oprf-nr
{%- endmacro -%}

{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | striptags | trim | upper_first }}
  {% for commit in commits
  | filter(attribute="scope")
  | sort(attribute="scope") %}
    - *({{ commit.scope }})* {{ commit.message | upper_first }} \
      ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
  {%- endfor -%}
  {% for commit in commits %}
    {%- if not commit.scope %}
    - {{ commit.message | upper_first }} \
      ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
    {% endif -%}
  {% endfor -%}
{% endfor %}
"""
footer = """
<!-- generated by git-cliff -->
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/TaceoLabs/oprf-nr/pull/${2}))" },
]
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->🚀 Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 3 -->🔧 Refactor" },
  { message = "^doc", group = "<!-- 4 -->📚 Documentation" },
  { message = "^style", group = "<!-- 5 -->🎨 Styling" },
  { message = "^test", group = "<!-- 6 -->🧪 Testing" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(deps.*\\)", group = "<!-- 7 -->📦 Dependencies" },
  { message = "^chore|^ci", group = "<!-- 8 -->⚙️ Miscellaneous" },
  { body = ".*security", group = "<!-- 9 -->🔒 Security" },
  { message = "^revert", group = "<!-- 10 -->◀️ Reverts" },
]
protect_breaking_commits = false
filter_commits = false
topo_order = false
sort_commits = "oldest"
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
